language: ruby
rvm:
- 2.0.0
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIBD6L2JBW743RTFA
    - secure: Nci/ufgrjCz9ol7tiQnFN/8cM3mR4YumVtKOXovgmp78P1FgzId9DI+wZNe1yHTWXLpsrQD0T8kX9WN6RWEo3SD4/aAK1DvQWikJlQIAR1D1I8mDlfvGMo+Npnvfu6Z8chndW3tjYPQOxF4xlfu9kI88njzYSEc2KXO8TSzXOak=
script:
- bundle exec roadwork -t
after_script:
- bundle exec roadwork -a
